apiVersion: apps/v1
kind: Deployment
metadata:
  name: weit-api
spec:
  template:
    spec:
      containers:
        - name: weit-api
          env:
            - name: APP_PHASE
              value: stable
      nodeSelector:
        performance: high