apiVersion: apps/v1
kind: Deployment
metadata:
  name: weit-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: weit-api
    spec:
      containers:
        - name: weit-api
          image: ghcr.io/konempty/temp:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 400Mi
          ports:
            - containerPort: 8080
          env:
            - name: APP_PHASE
              value: sandbox
            - name: APP_NAME
              value: weit-api
            - name: JAVA_TOOL_OPTIONS
              value: >
                -XX:InitialRAMPercentage=50
                -XX:MaxRAMPercentage=80
                -XX:MinRAMPercentage=80
          readinessProbe:
            httpGet:
              port: 8080
              path: /ready
            initialDelaySeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 130
            timeoutSeconds: 10
            failureThreshold: 10
      volumes:
        - name: share-vol
          emptyDir: {}
      imagePullSecrets:
        - name: ghcr-login-secret
