apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
namespace: sandbox

resources:
- ../../base
- ./ingress.yaml

images:
- name: ghcr.io/konempty/temp
  newTag: sandbox

patchesStrategicMerge:
- patch.yaml
- deployment.yaml
